version: '3'

services:
  bfv:
    build:
      context: .
    image: battlefield_vietnam_eod
    container_name: battlefield_vietnam
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./settings/:/usr/bin/bfv/mods/bfvietnam/settings/ # server settings
    ports:
      - "5711:5711"  # Remote Console Port
      - "14690:14690/udp" # All-Seeing Eye (ASE)
      - "15567:15567/udp" # Battlefield Vietnam
      - "15667:15667"  # Battlefield Server Manager (BFSM)
      - "22000:22000/udp" # GameSpy Internet
      - "23000:23000/udp" # GameSpy LAN
      - "27900:27900/udp" # Publish server to GameSpy
      - "27910:27910/udp" # Client CDKey check to GameSpy
    command: -start -restart \@server Admin.enableremoteadmin DockerBFV
